services:
  db:
    image: postgres:16
    container_name: internship_tracker_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env.docker
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    command: postgres -c 'listen_addresses=*'

volumes:
  db_data: